// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbY9HHyH9lRFB81pdGPBOmyi03Pl2_c5I',
    appId: '1:683073478014:web:b025fc39065a42dda9a72f',
    messagingSenderId: '683073478014',
    projectId: 'fish-f6e35',
    authDomain: 'fish-f6e35.firebaseapp.com',
    storageBucket: 'fish-f6e35.appspot.com',
    measurementId: 'G-XRSPJRKDL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBdrGqy9s6V-8hi6-cCnLGhMoW_5BqVYU',
    appId: '1:683073478014:android:1b41c375fe6f3b89a9a72f',
    messagingSenderId: '683073478014',
    projectId: 'fish-f6e35',
    storageBucket: 'fish-f6e35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqlrmtLLXQEDiAxsa19RmrN60qHDQlewI',
    appId: '1:683073478014:ios:0dcdb2989a1e79c9a9a72f',
    messagingSenderId: '683073478014',
    projectId: 'fish-f6e35',
    storageBucket: 'fish-f6e35.appspot.com',
    iosClientId: '683073478014-9fm3eufp8rhc1ksd551ol18nod45iqe3.apps.googleusercontent.com',
    iosBundleId: 'com.example.testpoj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqlrmtLLXQEDiAxsa19RmrN60qHDQlewI',
    appId: '1:683073478014:ios:0dcdb2989a1e79c9a9a72f',
    messagingSenderId: '683073478014',
    projectId: 'fish-f6e35',
    storageBucket: 'fish-f6e35.appspot.com',
    iosClientId: '683073478014-9fm3eufp8rhc1ksd551ol18nod45iqe3.apps.googleusercontent.com',
    iosBundleId: 'com.example.testpoj',
  );
}
